dist: trusty
sudo: required
language: c

before_install:
- chmod +x ./script/deps.sh

install:
- sudo ./script/deps.sh

script:
- make init
- make build MODE=static
- make clean
- make init
- make build MODE=dynamic
- make clean
