dist: trusty
sudo: required
language: cpp

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get -qq install g++-7
  - g++ --version
  - g++-7 --version
  - chmod +x ./script/deps.sh

install:
  - sudo ./script/deps.sh

script:
  - make init CC=g++-7
  - make all CC=g++-7
  - make test CC=g++-7
  - make clean CC=g++-7
